@startuml
title Sequence Diagram about Compilation to Intermediate Language
autonumber

boundary ILCompiler
entity ILInstruction
database ILInstructionRepository

box ILCompilationContext
    participant ILCompiler
    participant ILInstruction
    participant ILInstructionRepository
end box

== Compilation to Intermediate Language ==
--> ILCompiler : ValidFunctions
ILCompiler --> ILInstruction: ValidFunctions
ILCompiler <-- ILInstruction: ILInstructions
ILCompiler --> ILInstructionRepository: ILInstructions

@enduml